Repository Team-Stuckyi/TheGreatCatsby-FrontEnd, pull requests merged in 2022-03, with the labels that each got.

#52 [Merge] MainPage 페이지 구현
  src/App.js
  src/components/users/ListBar.js
  src/components/users/ProdCard.js
  src/components/users/Tabs.js
  src/index.js
  src/pages/users/Main.js
  src/slices/users/MainProductSlice.js
  src/store.js
Labels: feature

#68 [Merge] 리뷰 페이지 개발 (main <- Review)
  src/components/common/ReviewList.js
  src/components/users/ProdReviewInfo.js
  src/components/users/ReviewWrite.js
  src/img/noImg.png
  src/pages/users/Review.js
  src/slices/users/ReviewListSlice.js
  src/slices/users/ReviewProdInfoSlice.js
  src/slices/users/ReviewWriteSlice.js
Labels: feature

#71 [Merge] 관리자 페이지 -리뷰 관리자 (main <- ManageReview)
  src/components/common/Alert.js
  src/components/common/TableList.js
  src/pages/admin/ManageReview.js
  src/slices/admin/AdminReviewListSlice.js
Labels: feature

#74 [Merge] 관리자 페이지 - 관리자 회원 관리
  src/pages/admin/ManageAdmin.js
  src/slices/admin/AdminUserSlice.js
  src/store.js
Labels: feature

#75 [Merge] 관리자 페이지 - 일반 회원 관리
  src/pages/admin/ManageMember.js
  src/slices/admin/MemberSlice.js
Labels: feature

#76 ProdList.js 페이지 기능 개발 완료
  src/components/users/ProdBuy.js
  src/components/users/ProdImg.js
  src/components/users/ProdInfo.js
  src/components/users/ProdReview.js
  src/pages/users/ProdList.js
Labels: feature, fix

#77 AdminLogin.js
  package-lock.json
  package.json
  src/components/common/Search.js
  src/components/common/Title.js
  src/css/AdminLogin.css
  src/css/color.module.scss
  src/pages/admin/AdminLogin.js
  src/slices/admin/LoginSlice.js
  src/slices/admin/appSlice.js
  src/store.js
  yarn.lock
Labels: fix

#78 Thankyou.js Showmethemoney.js 페이지 및 컴포넌트
  src/components/common/Alert.js
  src/components/common/Input.js
  src/components/common/Logo.js
  src/components/pages/Thankyou.js
  src/components/users/Header.js
  src/components/users/NewAdress.js
  src/components/users/PayAdress.js
  src/components/users/PayMent.js
  src/components/users/ProdOrder.js
  src/components/users/RecentAdress.js
  src/pages/users/Showmethemoney.js
  src/pages/users/Thankyou.js
  src/slices/users/NewMemberSlice.js
  src/slices/users/RecentMemberSlice.js
  src/slices/users/ShowOrderSlice.js
Labels: feature

#79 Admin Login, ProdList Page bugfix
  src/components/users/ProdReview.js
  src/pages/admin/AdminLogin.js
  src/pages/users/ProdList.js
  src/slices/admin/adminAppSlice.js
  src/slices/admin/adminLoginSlice.js
  src/store.js
Labels: update, fix
